### ISSUE TITLE
ERR_REQUIRE_ESM v5.x

### ISSUE THREAD

**Issue by vkryman** [101arrowz/fflate#34]
yarn v1.22.10; node v14.15.0; webpack v5.13.0

Hello, I did not have a problem with previous versions of the fflate v4.x but starting from v5.0:

// client side (browser) webworker
import { gunzipSync } from 'fflate';
...
webpack 5.13.0 compiled successfully in 10038 ms
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /../node_modules/fflate/esm/index.mjs
    at Module.load (internal/modules/cjs/loader.js:926:11)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.fflate (/../build/bundle.js:1069:18)
    at __webpack_require__ (/../build/bundle.js:1332:41)
    at eval (webpack://mpd-eds/./src/client/components/decompressFileContent.js?:17:64)
    at Object../src/client/components/decompressFileContent.js (/../build/bundle.js:599:1)
    at __webpack_require__ (/../build/bundle.js:1332:41)
    at eval (webpack://mpd-eds/./src/client/actions/initState.js?:57:91) {
  code: 'ERR_REQUIRE_ESM'
}
[nodemon] app crashed - waiting for file changes before starting...
...

**Comment by 101arrowz** [comment]
That looks like the error is happening in Node.js. Could you add your Webpack config, `package.json`, etc.? Creating a reproducible repo is also helpful.

**Comment by vkryman** [comment]
For me will be very difficult to reproduce the error in minified project, maybe later if you do not understand the problem...
[fflate.zip](https://github.com/101arrowz/fflate/files/5813350/fflate.zip)

**Comment by 101arrowz** [comment]
This should be fixed in v0.5.3; could you try updating?

**Comment by vkryman** [comment]
Now it works fine. Many thanks for your attention...

**Comment by vkryman** [comment]
Oops... I've found the same issue as before for v0.6.0

**Comment by 101arrowz** [comment]
I'm going to look for a longer term fix for this, sorry about the bugs...

**Comment by 101arrowz** [comment]
I finally managed to reproduce, find, and fix the bug. Let me know if v0.6.1 on NPM fixes the issues.

**Comment by vkryman** [comment]
Yup, it works again for v0.6.1. Thanks a lot...
